custom:
  defaultStage: beta
  es_endpoint:
    prod: search-lifecycles-6g4ietujf5awnjqgh3fzrzacci.eu-west-1.es.amazonaws.com
    beta: search-lifecycles-beta-sawumn4sfwcrlcqkx7vh6kdve4.us-east-1.es.amazonaws.com
  es_domain:
    prod: lifecycles
    beta: lifecycles-beta
  region:
    prod: eu-west-1
    beta: us-east-1
  delete_after:
    prod: "60"
    beta: "30"
  deploymentBucket:
    prod: smartcosmos.lambda.repo
    beta: net.smartcosmos.switches

# serverless.yml
service: es-cleanup-lambda

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.region.${self:provider.stage}}
  profile: ${env:AWS_DEFAULT_PROFILE}
  deploymentBucket: ${self:custom.deploymentBucket.${self:provider.stage}}
  environment:
    es_endpoint: ${self:custom.es_endpoint.${self:provider.stage}}
    index: logstash
    delete_after: ${self:custom.delete_after.${self:provider.stage}}
    index_format: "%Y.%m.%d"
  stackTags: # Optional CF stack tags
    Owner: Peter Simon
    Purpose: es-cleanup
    Solution: lifecycles
    Env: ${self:provider.stage}
    Org: SMARTCOSMOS
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "es:*"
      Resource: "arn:aws:es:${self:provider.region}:758616332952:domain/${self:custom.es_domain.${self:provider.stage}}/*"
      # you must psecify the full ARN 


functions:
  es-cleanup-lambda:
    handler: es-cleanup.lambda_handler 
    name: es-cleanup-lambda 
    description: ES old index removal 
    runtime: python2.7 
    memorySize: "128"
    timeout: 180 
    package:
      exclude:
        - ./**
      include:
        - es-cleanup.py
        - LICENSE.md
        - README.md
        - CONTRIBUTING.md
    events:
      # Invoke Lambda function every night at 01.00 AM
      - schedule: cron(0 1 * * ? *)    
